#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat >&2 <<'EOF'
usage: scripts/canary/railgun-x402-funded-canary.sh [--replay-check]

Submits a funded Railgun/EVM x402 proof JSON to the Ghola OpenAI-compatible
chat endpoint. The proof JSON must be generated by the user/agent Railgun
wallet flow and must already contain scheme=railgun_evm_shielded.

Required:
  RAILGUN_X402_PROOF_JSON   path to x402 proof JSON

Optional:
  GHOLA_V1_CHAT_URL         default: https://ghola.xyz/v1/chat/completions
  GHOLA_CANARY_MODEL        default: agent:research-bot
  GHOLA_CANARY_PROMPT       default: Railgun funded canary. Reply with ok.
  GHOLA_API_KEY             optional bearer token
  GHOLA_OHTTP_RELAY_URL     when set, run through OHTTP instead of direct curl
  GHOLA_OHTTP_KEYS_URL      optional OHTTP keyconfig URL for OHTTP mode
  GHOLA_RELAY_BASE_URL      default OHTTP key base: https://ghola-relay.onrender.com

The script expects the first request to return 2xx. With --replay-check, it
sends the same proof again and expects rejection.
EOF
}

need() {
  command -v "$1" >/dev/null 2>&1 || {
    printf 'missing required command: %s\n' "$1" >&2
    exit 127
  }
}

encode_payment_header() {
  node - "$1" <<'NODE'
const fs = require('node:fs');
const file = process.argv[2];
const proof = JSON.parse(fs.readFileSync(file, 'utf8'));
if (proof.scheme !== 'railgun_evm_shielded') {
  throw new Error('proof.scheme must be railgun_evm_shielded');
}
if (proof.network == null || proof.payload?.extensions?.railgun == null) {
  throw new Error('proof must include network and payload.extensions.railgun');
}
process.stdout.write(Buffer.from(JSON.stringify(proof), 'utf8').toString('base64'));
NODE
}

REPLAY_CHECK=false
args=()
while [ "$#" -gt 0 ]; do
  case "$1" in
    --replay-check)
      REPLAY_CHECK=true
      args+=("$1")
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      usage
      exit 2
      ;;
  esac
  shift
done

need node

if [ -n "${GHOLA_OHTTP_RELAY_URL:-}" ]; then
  script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
  exec node "$script_dir/railgun-x402-ohttp-funded-canary.mjs" "${args[@]}"
fi

need curl

PROOF_JSON="${RAILGUN_X402_PROOF_JSON:-}"
if [ -z "$PROOF_JSON" ]; then
  printf 'RAILGUN_X402_PROOF_JSON is required\n' >&2
  exit 2
fi
if [ ! -f "$PROOF_JSON" ]; then
  printf 'proof JSON not found: %s\n' "$PROOF_JSON" >&2
  exit 2
fi

CHAT_URL="${GHOLA_V1_CHAT_URL:-https://ghola.xyz/v1/chat/completions}"
MODEL="${GHOLA_CANARY_MODEL:-agent:research-bot}"
PROMPT="${GHOLA_CANARY_PROMPT:-Railgun funded canary. Reply with ok.}"
PAYMENT_HEADER="$(encode_payment_header "$PROOF_JSON")"
body="$(mktemp)"
trap 'rm -f "$body" "${replay_body:-}"' EXIT

auth_args=()
if [ -n "${GHOLA_API_KEY:-}" ]; then
  auth_args=(-H "Authorization: Bearer ${GHOLA_API_KEY}")
fi

status="$(
  curl -sS -o "$body" -w '%{http_code}' \
    -X POST "$CHAT_URL" \
    -H 'content-type: application/json' \
    -H 'x-ghola-payment-rail: railgun_evm_shielded' \
    -H "x402-payment: ${PAYMENT_HEADER}" \
    -H "payment-signature: ${PAYMENT_HEADER}" \
    "${auth_args[@]}" \
    --data "$(printf '{"model":%s,"messages":[{"role":"user","content":%s}],"max_tokens":32}' \
      "$(node -e 'process.stdout.write(JSON.stringify(process.argv[1]))' "$MODEL")" \
      "$(node -e 'process.stdout.write(JSON.stringify(process.argv[1]))' "$PROMPT")")"
)"

case "$status" in
  2??)
    printf 'Railgun funded x402 canary accepted by %s (HTTP %s).\n' "$CHAT_URL" "$status" >&2
    ;;
  *)
    printf 'Railgun funded x402 canary failed with HTTP %s\n' "$status" >&2
    cat "$body" >&2
    exit 1
    ;;
esac

if [ "$REPLAY_CHECK" = true ]; then
  replay_body="$(mktemp)"
  replay_status="$(
    curl -sS -o "$replay_body" -w '%{http_code}' \
      -X POST "$CHAT_URL" \
      -H 'content-type: application/json' \
      -H 'x-ghola-payment-rail: railgun_evm_shielded' \
      -H "x402-payment: ${PAYMENT_HEADER}" \
      -H "payment-signature: ${PAYMENT_HEADER}" \
      "${auth_args[@]}" \
      --data "$(printf '{"model":%s,"messages":[{"role":"user","content":"Replay check. This should be rejected."}],"max_tokens":16}' \
        "$(node -e 'process.stdout.write(JSON.stringify(process.argv[1]))' "$MODEL")")"
  )"
  case "$replay_status" in
    2??)
      printf 'replay check unexpectedly succeeded (HTTP %s)\n' "$replay_status" >&2
      cat "$replay_body" >&2
      exit 1
      ;;
    *)
      printf 'Replay check rejected as expected (HTTP %s).\n' "$replay_status" >&2
      ;;
  esac
fi

cat "$body"
