export type VenueId = "hyperliquid" | "lighter" | "aster" | "edgex" | "dydx" | "variational_omni" | "drift" | "phoenix" | "backpack" | "coinbase_advanced" | "jupiter";
export type CorePerpVenueId = "hyperliquid" | "lighter" | "aster" | "edgex" | "dydx";
export type CarryExecutionVenueId = "hyperliquid" | "lighter" | "aster";
export type StrategyId = "best_execution" | "spot_perp_hedge" | "delta_neutral_carry" | "exposure_rebalance";
export declare const EXECUTION_CORE_VERSION: 1;
export declare const SUPPORTED_EXECUTION_VENUES: readonly VenueId[];
export declare const CORE_PERP_VENUES: readonly CorePerpVenueId[];
export declare const CARRY_EXECUTION_VENUES: readonly CarryExecutionVenueId[];
export declare const CARRY_BROWSER_STREAM_VENUES: readonly CorePerpVenueId[];
export declare const EXECUTION_VENUE_SPECS: Readonly<Record<VenueId, Readonly<Record<string, unknown>>>>;
export declare const SUPPORTED_STRATEGIES: readonly StrategyId[];
export declare const PORTFOLIO_SIGNING_BOUNDARY: Readonly<Record<string, readonly string[]>>;
export declare class ExecutionCoreError extends Error { code: string; }
export declare class CarryModelError extends Error { code: string; }
export declare function executionVenueSpec(venueId: string): Readonly<Record<string, unknown>> | null;
export declare function exactQuantityRecoveryAdapter(venueId: string): string | null;
export declare function isExecutionVenue(venueId: string): boolean;
export declare function isCarryExecutionVenue(venueId: string): boolean;
export declare function supportsExactQuantityRecovery(venueId: string): boolean;
export declare function venueAdapterCapability(venueId: string, capability: string): Readonly<Record<string, unknown>> | null;
export declare function venuesWithAdapterCapability(capability: string, options?: { cohort?: string | null; product?: string | null; statuses?: readonly string[] }): readonly VenueId[];
export declare function venueSupportsProduct(venueId: string, productType: string): boolean;
export declare function requiredVenueCapabilities(input: Record<string, unknown>): readonly string[];
export declare function normalizePortfolioMandate(value: unknown): Readonly<Record<string, unknown>>;
export declare function normalizePortfolioState(value: unknown): Readonly<Record<string, unknown>>;
export declare function assessVenueReadiness(input: Record<string, unknown>): Readonly<Record<string, unknown>>;
export declare function rankExecutionRoutes(input: Record<string, unknown>): Readonly<Record<string, unknown>>;
export declare function evaluatePortfolioPlan(input: Record<string, unknown>): Readonly<Record<string, unknown>>;
export declare function createMultiLegSaga(input: Record<string, unknown>): Readonly<Record<string, unknown>>;
export declare function advanceMultiLegSaga(input: Record<string, unknown>): Readonly<Record<string, unknown>>;
export declare function normalizeVenueAccountingSnapshot(input: unknown): Readonly<Record<string, unknown>>;
export declare function aggregatePortfolioAccounting(input: Record<string, unknown>): Readonly<Record<string, unknown>>;
export declare function reconcilePortfolioAccounting(input: Record<string, unknown>): Readonly<Record<string, unknown>>;
export declare function buildExecutionQualityReceipt(input: unknown): Readonly<Record<string, unknown>>;
export declare function aggregateExecutionQuality(input: unknown[]): Readonly<Record<string, unknown>>;
export declare function normalizePerpContractSpec(input: unknown): Readonly<Record<string, unknown>>;
export declare function calculateMarginRunway(input: unknown): Readonly<Record<string, unknown>>;
export declare function compileCarryCapitalActionPlan(input: unknown): Readonly<Record<string, unknown>>;
export declare function evaluatePerpContractPairBasis(input: unknown): Readonly<Record<string, unknown>>;
export declare function evaluateCarryOpportunity(input: unknown): Readonly<Record<string, unknown>>;
export declare function compileCarryMigrationProposal(input: unknown): Readonly<Record<string, unknown>>;
export declare function normalizeCarryRiskMandate(input: unknown): Readonly<Record<string, unknown>>;
export declare function normalizeCarryRiskMandatePayload(input: unknown): Readonly<Record<string, unknown>>;
export declare function normalizeCarryRiskMandateAuthorization(input: unknown): Readonly<Record<string, unknown>>;
export declare function carryRiskMandateMessage(input: unknown): string;
export declare function createCarryPosition(input: unknown): Readonly<Record<string, unknown>>;
export declare function advanceCarryPosition(input: Record<string, unknown>): Readonly<Record<string, unknown>>;
export declare function createCarryValueLedger(input: unknown): Readonly<Record<string, unknown>>;
export declare function appendCarryValueLedgerEntry(input: Record<string, unknown>): Readonly<Record<string, unknown>>;
export declare function finalizeCarryValueLedger(input: Record<string, unknown>): Readonly<Record<string, unknown>>;
