export type VenueId = "hyperliquid" | "lighter" | "aster" | "edgex" | "dydx" | "variational_omni" | "drift" | "phoenix" | "backpack" | "coinbase_advanced" | "jupiter";
export type CorePerpVenueId = "hyperliquid" | "lighter" | "aster" | "edgex" | "dydx";
export type CarryExecutionVenueId = "hyperliquid" | "lighter" | "aster";
export type StrategyId = "best_execution" | "spot_perp_hedge" | "delta_neutral_carry" | "exposure_rebalance";
export declare const EXECUTION_CORE_VERSION: 1;
export declare const SUPPORTED_EXECUTION_VENUES: readonly VenueId[];
export declare const CORE_PERP_VENUES: readonly CorePerpVenueId[];
export declare const CARRY_EXECUTION_VENUES: readonly CarryExecutionVenueId[];
export declare const CARRY_EXECUTION_REQUIRED_ADAPTER_CAPABILITIES: readonly ["carry_execution", "no_submit_reconciliation", "exact_quantity_recovery"];
export declare const CARRY_RECOVERY_POLICY: Readonly<{
  ambiguous_submission: "freeze_reconcile_never_retry";
  partial_fill: "exact_quantity_reduce_only";
  worker_restart: "reconcile_before_action";
}>;
export declare const CARRY_BROWSER_STREAM_VENUES: readonly CorePerpVenueId[];
export declare const EXECUTION_VENUE_SPECS: Readonly<Record<VenueId, Readonly<Record<string, unknown>>>>;
export declare const SUPPORTED_STRATEGIES: readonly StrategyId[];
export declare const PORTFOLIO_SIGNING_BOUNDARY: Readonly<Record<string, readonly string[]>>;
export declare class ExecutionCoreError extends Error { code: string; }
export declare class CarryModelError extends Error { code: string; }
export declare function executionVenueSpec(venueId: string): Readonly<Record<string, unknown>> | null;
export declare function carryExecutionQualification(venueId: string): Readonly<{ venue_id: string; eligible: boolean; gaps: readonly string[] }>;
export declare function exactQuantityRecoveryAdapter(venueId: string): string | null;
export declare function isExecutionVenue(venueId: string): boolean;
export declare function isCarryExecutionVenue(venueId: string): boolean;
export declare function supportsExactQuantityRecovery(venueId: string): boolean;
export declare function venueAdapterCapability(venueId: string, capability: string): Readonly<Record<string, unknown>> | null;
export declare function venuesWithAdapterCapability(capability: string, options?: { cohort?: string | null; product?: string | null; statuses?: readonly string[] }): readonly VenueId[];
export declare function venueSupportsProduct(venueId: string, productType: string): boolean;
export declare function requiredVenueCapabilities(input: Record<string, unknown>): readonly string[];
export declare function normalizePortfolioMandate(value: unknown): Readonly<Record<string, unknown>>;
export declare function normalizePortfolioState(value: unknown): Readonly<Record<string, unknown>>;
export declare function assessVenueReadiness(input: Record<string, unknown>): Readonly<Record<string, unknown>>;
export declare function rankExecutionRoutes(input: Record<string, unknown>): Readonly<Record<string, unknown>>;
export declare function evaluatePortfolioPlan(input: Record<string, unknown>): Readonly<Record<string, unknown>>;
export declare function createMultiLegSaga(input: Record<string, unknown>): Readonly<Record<string, unknown>>;
export declare function advanceMultiLegSaga(input: Record<string, unknown>): Readonly<Record<string, unknown>>;
export declare function normalizeVenueAccountingSnapshot(input: unknown): Readonly<Record<string, unknown>>;
export declare function aggregatePortfolioAccounting(input: Record<string, unknown>): Readonly<Record<string, unknown>>;
export declare function reconcilePortfolioAccounting(input: Record<string, unknown>): Readonly<Record<string, unknown>>;
export declare function buildExecutionQualityReceipt(input: unknown): Readonly<Record<string, unknown>>;
export declare function aggregateExecutionQuality(input: unknown[]): Readonly<Record<string, unknown>>;
export declare function normalizePerpContractSpec(input: unknown): Readonly<Record<string, unknown>>;
export declare function canonicalCarryCommitmentJson(input: unknown): string;
export declare function calculateMarginRunway(input: unknown): Readonly<Record<string, unknown>>;
export declare function compileCarryCapitalActionPlan(input: unknown): Readonly<Record<string, unknown>>;
export declare function compileCarryCollateralReview(input: unknown): Readonly<Record<string, unknown>>;
export declare function compileCarryPortfolioCapitalPlan(input: unknown): Readonly<Record<string, unknown>>;
export declare function compileCarryPortfolioValueReport(input: unknown): Readonly<Record<string, unknown>>;
export type CarryLifecycleValueAttribution = Readonly<{
  modeled: Readonly<{
    gross_funding_micro_usdc: number;
    total_cost_micro_usdc: number;
    expected_net_micro_usdc: number;
  }>;
  realized: Readonly<{
    contract_pnl_micro_usdc: number;
    funding_micro_usdc: number;
    fees_micro_usdc: number;
    slippage_micro_usdc: number;
    gas_micro_usdc: number;
    capital_cost_micro_usdc: number;
    transfer_fees_micro_usdc: number;
    rebates_micro_usdc: number;
    net_value_micro_usdc: number;
  }>;
  realized_total_cost_micro_usdc: number;
  variance_from_modeled_micro_usdc: number;
}>;
export declare function normalizeCarryLifecycleValueAttribution(input: unknown): CarryLifecycleValueAttribution;
export declare function evaluatePerpContractPairBasis(input: unknown): Readonly<Record<string, unknown>>;
export declare function estimatePerpDepthExecution(input: {
  side: "buy" | "sell";
  depth_levels?: readonly { price_e8: number; size_e8: number }[] | null;
  fallback_price_e8?: number | null;
  target_notional_micro_usdc: number;
  phase?: string;
}): Readonly<{
  phase: string;
  side: "buy" | "sell";
  status: "sufficient" | "insufficient" | "unavailable";
  target_notional_micro_usdc: number;
  displayed_notional_micro_usdc: number;
  execution_price_e8: number | null;
}>;
export declare function adverseExecutionSlippageE6Bps(input: {
  side: "buy" | "sell";
  mark_price_e8: number | null | undefined;
  execution_price_e8: number | null | undefined;
}): number;
export declare function evaluateCarryOpportunity(input: unknown): Readonly<Record<string, unknown>>;
export declare function compileCarryMigrationProposal(input: unknown): Readonly<Record<string, unknown>>;
export declare function normalizeCarryRiskMandate(input: unknown): Readonly<Record<string, unknown>>;
export declare function normalizeCarryCollateralReviewPayload(input: unknown): Readonly<Record<string, unknown>>;
export declare function normalizeCarryCollateralReviewAuthorization(input: unknown): Readonly<Record<string, unknown>>;
export declare function carryCollateralReviewMessage(input: unknown): string;
export declare function normalizeCarryRiskMandatePayload(input: unknown): Readonly<Record<string, unknown>>;
export declare function normalizeCarryRiskMandateAuthorization(input: unknown): Readonly<Record<string, unknown>>;
export declare function carryRiskMandateMessage(input: unknown): string;
export declare function createCarryPosition(input: unknown): Readonly<Record<string, unknown>>;
export declare function advanceCarryPosition(input: Record<string, unknown>): Readonly<Record<string, unknown>>;
export declare function createCarryValueLedger(input: unknown): Readonly<Record<string, unknown>>;
export declare function appendCarryValueLedgerEntry(input: Record<string, unknown>): Readonly<Record<string, unknown>>;
export declare function finalizeCarryValueLedger(input: Record<string, unknown>): Readonly<Record<string, unknown>>;
