#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="${GHOLA_PRIVATE_AGENT_STAGING_ENV:-$ROOT/.dev/private-agent-staging.env}"
PARTNER_POOL_EXAMPLE="$ROOT/.dev/coinbase-partner-pool-vault.example.json"

mkdir -p "$(dirname "$ENV_FILE")"

existing() {
  local name="$1"
  if [[ -f "$ENV_FILE" ]]; then
    node - "$ENV_FILE" "$name" <<'NODE'
const [file, name] = process.argv.slice(2);
const fs = require("node:fs");
const text = fs.readFileSync(file, "utf8");
for (const line of text.split(/\r?\n/)) {
  const match = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)=(.*)\s*$/);
  if (!match || match[1] !== name) continue;
  let value = match[2].trim();
  if (
    (value.startsWith("'") && value.endsWith("'")) ||
    (value.startsWith('"') && value.endsWith('"'))
  ) {
    value = value.slice(1, -1);
  }
  process.stdout.write(value);
  process.exit(0);
}
NODE
  fi
}

value_or_default() {
  local name="$1"
  local fallback="$2"
  local current
  current="$(existing "$name")"
  if [[ -n "$current" ]]; then
    printf '%s' "$current"
  else
    printf '%s' "$fallback"
  fi
}

token_default="$(node -e 'process.stdout.write(require("node:crypto").randomBytes(32).toString("base64url"))')"
worker_token="$(value_or_default PRIVATE_AGENT_EXECUTION_TOKEN "$token_default")"
worker_url="$(value_or_default PRIVATE_AGENT_WORKER_URL "http://127.0.0.1:8787")"
data_dir="$(value_or_default PRIVATE_AGENT_DATA_DIR "$ROOT/.dev/private-agent-worker-data")"

quote() {
  node - "$1" <<'NODE'
const value = process.argv[2] ?? "";
process.stdout.write(`'${value.replace(/'/g, "'\\''")}'`);
NODE
}

cat > "$ENV_FILE" <<EOF
# Generated by scripts/staging/private-agent-bootstrap-local.sh.
# This file is ignored by git via .dev/.

# Worker URL/token used by canary scripts.
PRIVATE_AGENT_WORKER_URL=$(quote "$worker_url")
PRIVATE_AGENT_EXECUTION_TOKEN=$(quote "$worker_token")

# Local staging worker env. This is dev-attested only; do not use as production evidence.
PORT='8787'
PRIVATE_AGENT_DATA_DIR=$(quote "$data_dir")
PRIVATE_AGENT_PROVIDER_ID='phala'
PRIVATE_AGENT_TEE_KIND='phala'
PRIVATE_AGENT_ALLOW_UNATTESTED_DEV='true'
PRIVATE_AGENT_ATTESTED_READY='true'
PRIVATE_AGENT_REQUIRE_DSTACK_QUOTE='false'
PHALA_CVM_IMAGE_DIGEST='sha256:local-staging-canary'
PRIVATE_AGENT_MEASUREMENT_HEX='local-staging-measurement'
PRIVATE_AGENT_ATTESTATION_HASH='local-staging-attestation'
PRIVATE_AGENT_GLOBAL_KILL_SWITCH='false'
PRIVATE_AGENT_VENUE_DRY_RUN='true'
PRIVATE_AGENT_MAX_VENUE_REQUESTS_PER_MINUTE='60'
PRIVATE_AGENT_MIN_ORDER_NOTIONAL_USD='0'
PRIVATE_AGENT_SOLANA_PERPS_LIVE_MODE='disabled'
PRIVATE_AGENT_SOLANA_PERPS_ALLOW_MAINNET='false'
PRIVATE_AGENT_SOLANA_PERPS_LIVE_MAX_NOTIONAL_USD='5'
PRIVATE_AGENT_SOLANA_RPC_URL=''
PRIVATE_AGENT_SOLANA_PERPS_PRIORITY_FEE_MICRO_LAMPORTS='0'

# Matching web env for a manually configured local/staging worker.
GHOLA_PRIVATE_AGENT_PROVIDER='phala'
GHOLA_PRIVATE_AGENT_EXECUTION_URL=$(quote "$worker_url")
GHOLA_PRIVATE_AGENT_EXECUTION_TOKEN=$(quote "$worker_token")
GHOLA_PRIVATE_AGENT_ATTESTED_READY='true'
GHOLA_PRIVATE_AGENT_RECIPIENT_ID=''
PHALA_ENCLAVE_X25519_PUB_HEX=''
PHALA_CVM_MEASUREMENT_HEX='local-staging-measurement'
PHALA_ATTESTATION_HASH='local-staging-attestation'
PHALA_CVM_IMAGE_DIGEST='sha256:local-staging-canary'

# Live venue canary controls. Leave GHOLA_RUN_LIVE_VENUE_CANARY=0 for local dry-run.
GHOLA_RUN_LIVE_VENUE_CANARY='0'
GHOLA_CANARY_SUBMIT_ORDER='0'
GHOLA_CANARY_ACK_TINY_ORDER_RISK='0'
GHOLA_CANARY_VENUE='hyperliquid'

# Hyperliquid canary credential. Use testnet first.
GHOLA_CANARY_HYPERLIQUID_NETWORK='testnet'
GHOLA_CANARY_HYPERLIQUID_ACCOUNT_ADDRESS=''
GHOLA_CANARY_HYPERLIQUID_API_WALLET_PRIVATE_KEY=''
GHOLA_CANARY_HYPERLIQUID_MARKET='BTC'
GHOLA_CANARY_HYPERLIQUID_SIDE='buy'
GHOLA_CANARY_HYPERLIQUID_BASE_SIZE='0.001'
GHOLA_CANARY_HYPERLIQUID_LIMIT_PRICE='10000'

# Phoenix canary credential. Use a dedicated funded trader authority for live.
GHOLA_CANARY_PHOENIX_AUTHORITY_PRIVATE_KEY=''
GHOLA_CANARY_PHOENIX_MARKET='SOL'
GHOLA_CANARY_PHOENIX_SIDE='buy'
GHOLA_CANARY_PHOENIX_QUOTE_SIZE='5'
GHOLA_CANARY_PHOENIX_LIMIT_PRICE='250'
GHOLA_CANARY_SOLANA_RPC_URL=''
GHOLA_CANARY_PHOENIX_API_URL=''

# Coinbase BYO canary credential. Prefer sandbox. Provide either PEM_B64 or PEM_PATH.
GHOLA_CANARY_COINBASE_NETWORK='sandbox'
GHOLA_CANARY_COINBASE_API_KEY_NAME=''
GHOLA_CANARY_COINBASE_API_PRIVATE_KEY_PEM_B64=''
GHOLA_CANARY_COINBASE_API_PRIVATE_KEY_PEM_PATH=''
GHOLA_CANARY_COINBASE_PORTFOLIO_ID=''
GHOLA_CANARY_COINBASE_PRODUCT_ID='BTC-USD'
GHOLA_CANARY_COINBASE_SIDE='buy'
GHOLA_CANARY_COINBASE_BASE_SIZE='0.001'
GHOLA_CANARY_COINBASE_LIMIT_PRICE='10000'

# Coinbase partner omnibus live mode needs this set inside the worker/TEE.
PRIVATE_AGENT_COINBASE_PARTNER_POOL_VAULT_PATH=''
PRIVATE_AGENT_COINBASE_PARTNER_POOL_VAULT_JSON=''
EOF

if [[ ! -f "$PARTNER_POOL_EXAMPLE" ]]; then
  cat > "$PARTNER_POOL_EXAMPLE" <<'EOF'
{
  "kind": "ghola_coinbase_advanced_execution_vault",
  "network": "sandbox",
  "base_url": "https://api-sandbox.coinbase.com/api/v3/brokerage",
  "api_key_name": "organizations/<org-id>/apiKeys/<key-id>",
  "api_private_key_pem": "-----BEGIN EC PRIVATE KEY-----\n...\n-----END EC PRIVATE KEY-----",
  "portfolio_id": null
}
EOF
fi

cat <<EOF
Wrote local staging env:
  $ENV_FILE

Generated/preserved worker token:
  PRIVATE_AGENT_EXECUTION_TOKEN is set in the env file

Start a local staging worker:
  set -a; source "$ENV_FILE"; set +a
  cd "$ROOT/apps/private-agent-worker" && npm start

Run the sealed worker canary:
  set -a; source "$ENV_FILE"; set +a
  bash "$ROOT/scripts/canary/private-agent-worker-local.sh"

Run the venue canary in local dry-run mode:
  set -a; source "$ENV_FILE"; set +a
  node "$ROOT/scripts/canary/private-agent-venue-live.mjs"

For a real staging worker URL, set PHALA_CLOUD_API_KEY on the web deployment
or manually deploy apps/private-agent-worker/docker-compose.phala.yml to Phala,
then replace PRIVATE_AGENT_WORKER_URL/GHOLA_PRIVATE_AGENT_EXECUTION_URL with the
CVM HTTPS endpoint and keep this worker token as the shared auth secret.
EOF
