//! Read snarkjs verification_key.json → emit a Rust source file containing
//! the verifying key as a static byte-array tuple suitable for the on-chain
//! `groth16-solana` `Groth16Verifyingkey` struct.
//!
//! Run:
//!   cargo run -p said-shielded-pool-prover --example gen_vk_rs -- \
//!     ../said-shielded-pool-circuits/artifacts/verification_key.json \
//!     ../../programs/said-shielded-pool/src/verifying_key.rs
//!
//! Optional flags (must come AFTER the two positional args):
//!   --const-name <NAME>     name for the top-level `pub const` (default: VERIFYING_KEY)
//!   --module-doc <STR>      override the doc-comment header
//!
//! Example for the forester (batched-update) circuit:
//!   cargo run -p said-shielded-pool-prover --example gen_vk_rs -- \
//!     crates/said-shielded-pool-circuits/artifacts/forester_verification_key.json \
//!     programs/said-shielded-pool/src/forester_verifying_key.rs \
//!     --const-name VERIFYING_KEY \
//!     --module-doc "Forester (batched commitment-insertion) verifying key."

use ark_bn254::{Fq, Fq2, G1Affine, G2Affine};
use ark_ec::AffineRepr;
use ark_ff::{BigInteger, PrimeField};
use num_bigint::BigUint;
use serde_json::Value;
use std::env;
use std::fs;
use std::path::PathBuf;

fn parse_fq(s: &str) -> Fq {
    let n: BigUint = s.parse().expect("bad decimal in vk");
    Fq::from_be_bytes_mod_order(&n.to_bytes_be())
}
fn fq_to_be32(x: &Fq) -> [u8; 32] {
    let bi = x.into_bigint();
    let bytes = bi.to_bytes_be();
    let mut out = [0u8; 32];
    out[32 - bytes.len()..].copy_from_slice(&bytes);
    out
}
fn g1_to_be64(p: &G1Affine) -> [u8; 64] {
    let mut out = [0u8; 64];
    let (x, y) = p.xy().expect("infinity");
    out[..32].copy_from_slice(&fq_to_be32(&x));
    out[32..].copy_from_slice(&fq_to_be32(&y));
    out
}
fn g2_to_be128(p: &G2Affine) -> [u8; 128] {
    let mut out = [0u8; 128];
    let (x, y) = p.xy().expect("infinity");
    out[..32].copy_from_slice(&fq_to_be32(&x.c1));
    out[32..64].copy_from_slice(&fq_to_be32(&x.c0));
    out[64..96].copy_from_slice(&fq_to_be32(&y.c1));
    out[96..128].copy_from_slice(&fq_to_be32(&y.c0));
    out
}
fn parse_g1(arr: &Value) -> G1Affine {
    let x = parse_fq(arr[0].as_str().unwrap());
    let y = parse_fq(arr[1].as_str().unwrap());
    G1Affine::new(x, y)
}
fn parse_g2(arr: &Value) -> G2Affine {
    let x = Fq2::new(
        parse_fq(arr[0][0].as_str().unwrap()),
        parse_fq(arr[0][1].as_str().unwrap()),
    );
    let y = Fq2::new(
        parse_fq(arr[1][0].as_str().unwrap()),
        parse_fq(arr[1][1].as_str().unwrap()),
    );
    G2Affine::new(x, y)
}

fn emit_byte_array<const N: usize>(name: &str, b: &[u8; N]) -> String {
    let mut s = format!("pub const {}: [u8; {}] = [\n    ", name, N);
    for (i, byte) in b.iter().enumerate() {
        if i > 0 && i % 12 == 0 {
            s.push_str("\n    ");
        }
        s.push_str(&format!("0x{:02x}, ", byte));
    }
    s.push_str("\n];\n");
    s
}

fn main() {
    let args: Vec<String> = env::args().collect();
    if args.len() < 3 {
        eprintln!("usage: gen_vk_rs <vk.json> <out.rs> [--const-name NAME] [--module-doc STR]");
        std::process::exit(2);
    }
    let in_path = PathBuf::from(&args[1]);
    let out_path = PathBuf::from(&args[2]);

    let mut const_name = String::from("VERIFYING_KEY");
    let mut module_doc: Option<String> = None;
    let mut i = 3;
    while i < args.len() {
        match args[i].as_str() {
            "--const-name" => {
                const_name = args
                    .get(i + 1)
                    .expect("--const-name needs a value")
                    .clone();
                i += 2;
            }
            "--module-doc" => {
                module_doc = Some(
                    args.get(i + 1)
                        .expect("--module-doc needs a value")
                        .clone(),
                );
                i += 2;
            }
            other => {
                eprintln!("unknown flag: {other}");
                std::process::exit(2);
            }
        }
    }

    let vk_json: Value =
        serde_json::from_str(&fs::read_to_string(&in_path).unwrap()).unwrap();

    let alpha = g1_to_be64(&parse_g1(&vk_json["vk_alpha_1"]));
    let beta = g2_to_be128(&parse_g2(&vk_json["vk_beta_2"]));
    let gamma = g2_to_be128(&parse_g2(&vk_json["vk_gamma_2"]));
    let delta = g2_to_be128(&parse_g2(&vk_json["vk_delta_2"]));

    let ic_json = vk_json["IC"].as_array().unwrap();
    let n_pub = ic_json.len() - 1;
    let ic: Vec<[u8; 64]> = ic_json.iter().map(|g| g1_to_be64(&parse_g1(g))).collect();

    let mut src = String::new();
    let doc_line = module_doc
        .as_deref()
        .unwrap_or("Source ceremony: Hermez PoT + single contributor + beacon.");
    src.push_str(&format!(
        "//! AUTO-GENERATED by said-shielded-pool-prover/examples/gen_vk_rs.rs\n\
         //! DO NOT EDIT BY HAND — regenerate from the matching verification_key.json.\n\
         //!\n\
         //! {doc_line}\n\
         //! Production deployment MUST replace this with a multi-party (>=10) ceremony per SPEC.md §13.\n\n\
         use groth16_solana::groth16::Groth16Verifyingkey;\n\n",
    ));
    src.push_str(&format!("pub const NR_PUBINPUTS: usize = {};\n\n", n_pub));
    src.push_str(&emit_byte_array("VK_ALPHA_G1", &alpha));
    src.push_str("\n");
    src.push_str(&emit_byte_array("VK_BETA_G2", &beta));
    src.push_str("\n");
    src.push_str(&emit_byte_array("VK_GAMMA_G2", &gamma));
    src.push_str("\n");
    src.push_str(&emit_byte_array("VK_DELTA_G2", &delta));
    src.push_str("\n");

    src.push_str(&format!(
        "pub const VK_IC: [[u8; 64]; {}] = [\n",
        ic.len()
    ));
    for ic_pt in &ic {
        src.push_str("    [\n        ");
        for (i, byte) in ic_pt.iter().enumerate() {
            if i > 0 && i % 12 == 0 {
                src.push_str("\n        ");
            }
            src.push_str(&format!("0x{:02x}, ", byte));
        }
        src.push_str("\n    ],\n");
    }
    src.push_str("];\n\n");

    src.push_str(&format!(
        "pub const {const_name}: Groth16Verifyingkey = Groth16Verifyingkey {{\n\
         \x20   nr_pubinputs: NR_PUBINPUTS,\n\
         \x20   vk_alpha_g1: VK_ALPHA_G1,\n\
         \x20   vk_beta_g2: VK_BETA_G2,\n\
         \x20   vk_gamme_g2: VK_GAMMA_G2,\n\
         \x20   vk_delta_g2: VK_DELTA_G2,\n\
         \x20   vk_ic: &VK_IC,\n\
         }};\n",
    ));

    fs::write(&out_path, src).unwrap();
    println!("wrote {}", out_path.display());
    println!("  nr_pubinputs = {}", n_pub);
    println!("  vk_ic.len()  = {}", ic.len());
}
